<?php

use Drupal\Core\Entity\EntityInterface;

function autoslug_entity_insert(EntityInterface $entity) {
    autoslug_create_entity_alias($entity);
}

function autoslug_create_entity_alias(EntityInterface $entity) {
    $langcode = $entity->language()->getId();
    $config = Drupal::service('autoslug.config')->configForEntity($entity);

    if ($config) {
        $aliases = Drupal::service('path.alias_storage');

        if (!$url = $aliases->lookupPathAlias($entity->getSystemPath(), $langcode)) {
            if (!empty($config['path'])) {
                $pattern = $config['path'];
                $slugs = Drupal::service('autoslug.alias_generator');
                $alias = $slugs->aliasByPattern($entity, $pattern);
                $aliases->save($entity->getSystemPath(), $alias, $langcode);
            }
        }
    }
}

function autoslug_generate_entity_aliases() {
    $em = Drupal::entityManager();
    $node_storage = $em->getStorage('node');

    $counter = 0;

    foreach ($node_storage->loadMultiple(null) as $node) {
        autoslug_create_entity_alias($node);

        if ($counter++ % 10 == 0) {
            var_dump($counter);
            flush();
        }
    }
}

function autoslug_preprocess() {
    static $i = 0;

    if (!$i++ && isset($_GET['create_aliases'])) {
        autoslug_generate_entity_aliases();
    }
}
